<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="packages\**" />
    <EmbeddedResource Remove="packages\**" />
    <None Remove="packages\**" />
    <Page Remove="packages\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="Models\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Fluent.Ribbon" Version="11.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.5.26302.115" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="11.0.0-preview.5.26302.115" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib.CreoInteractionTools\MCG.CommonLib.CreoInteractionTools.csproj" />
    <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib.Resources\MCG.CommonLib.Resources.csproj" />
    <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib.WpfComponent\MCG.CommonLib.WpfComponent.csproj" />
    <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib\MCG.CommonLib.csproj" />
    <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.Converters\MCG.Converters.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.CadDocQualityCheck\MCG.CREO_Tools.CadDocQualityCheck.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.CutLengthApp\MCG.CREO_Tools.CutLengthApp.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.DxfExport\MCG.CREO_Tools.DxfExport.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.JpgExport\MCG.CREO_Tools.JpgExport.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.MassUpdateAttribute\MCG.CREO_Tools.MassUpdateAttribute.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.MiscTools\MCG.CREO_Tools.MiscTools.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.ProfileApp\MCG.CREO_Tools.ProfileApp.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.QuickLaunch\MCG.CREO_Tools.QuickLaunch.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.QuickSearch\MCG.CREO_Tools.QuickSearch.csproj" />
    <ProjectReference Include="..\MCG.CREO_Tools.ShearedTube\MCG.CREO_Tools.ShearedTube.csproj" />
    <ProjectReference Include="..\MCG.Tools.EcnDataCheck\MCG.Tools.EcnDataCheck.csproj" />
    <ProjectReference Include="..\MCG.Tools.EcnEcoFollowUp\MCG.Tools.EcnEcoFollowUp.csproj" />
    <ProjectReference Include="..\MCG.Tools.NumberingTool\MCG.Tools.NumberingTool.csproj" />
    <ProjectReference Include="..\MCG.Tools.PurchaseOrderFollowUp\MCG.Tools.PurchaseOrderFollowUp.csproj" />
    <ProjectReference Include="..\MCG.Tools.VisualizationLib\MCG.Tools.VisualizationLib.csproj" />
    <ProjectReference Include="..\MCG.WindchillTools.ManageWTObject\MCG.WindchillTools.ManageWTObject.csproj" />
  </ItemGroup>

</Project>
