<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Version>12.01.00</Version>
		<Authors>MCG</Authors>
		<Company>Manitowoc</Company>
		<Product>PurchaseOrderFollowUp</Product>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="Fluent.Ribbon" Version="11.0.2" />
	  <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
	  <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
	  <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib.DataBaseAccess\MCG.CommonLib.DataBaseAccess.csproj" />
	  <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib.SapTools\MCG.CommonLib.SapTools.csproj" />
	  <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib.WpfComponent\MCG.CommonLib.WpfComponent.csproj" />
	  <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.CommonLib\MCG.CommonLib.csproj" />
	  <ProjectReference Include="..\..\Net10.MCG.CommonLib\MCG.Converters\MCG.Converters.csproj" />
	</ItemGroup>

</Project>
